import { SERVICE_IDS, type ServiceId, type ServiceLocale, type ServicePageContent } from "./types";

const asset = (id: ServiceId, mobile = false) =>
  `/images/services/${id}-hero${mobile ? "-mobile" : ""}.webp`;

const slugs: Record<ServiceId, { en: string; es: string }> = {
  "long-distance-moving": { en: "long-distance-moving", es: "mudanzas-larga-distancia" },
  "auto-transport": { en: "auto-transport", es: "transporte-de-autos" },
  "military-moving": { en: "military-moving", es: "mudanzas-militares" },
  "residential-moving": { en: "residential-moving", es: "mudanzas-residenciales" },
  "corporate-office-moving": { en: "corporate-office-moving", es: "mudanzas-de-oficina" },
  "packing-services": { en: "packing-services", es: "servicios-de-embalaje" },
  "storage-options": { en: "storage-options", es: "opciones-de-almacenamiento" },
  "senior-moving": { en: "senior-moving", es: "mudanzas-para-personas-mayores" },
};

type Seed = Omit<ServicePageContent, "locale" | "slug" | "path" | "alternatePath" | "hero"> & {
  hero: Omit<ServicePageContent["hero"], "desktopImage" | "mobileImage">;
};

const commonProofEn = [
  { value: "USDOT 4078939", label: "Licensed moving broker" },
  { value: "MC 1551322", label: "Federal broker authority" },
  { value: "50 states", label: "Nationwide coordination" },
];
const commonProofEs = [
  { value: "USDOT 4078939", label: "Corredor de mudanzas con licencia" },
  { value: "MC 1551322", label: "Autoridad federal de corretaje" },
  { value: "50 estados", label: "Coordinación nacional" },
];

const quoteEn = (name: string) => ({
  title: `Plan Your ${name}`,
  subtitle: "Share a few move details. No obligation.",
  continueLabel: "Continue",
  submitLabel: "Request Free Quote",
  confirmationTitle: "Request Received",
  confirmationBody: "A Vantage moving coordinator will contact you shortly.",
});
const quoteEs = (name: string) => ({
  title: `Planifique ${name}`,
  subtitle: "Comparta algunos detalles. Sin obligación.",
  continueLabel: "Continuar",
  submitLabel: "Solicitar cotización",
  confirmationTitle: "Solicitud recibida",
  confirmationBody: "Un coordinador de Vantage se comunicará con usted pronto.",
});

const enSeeds: Record<ServiceId, Seed> = {
  "long-distance-moving": {
    id: "long-distance-moving", navLabel: "Long-Distance Moving",
    seo: { title: "Long-Distance Moving Coordination", description: "Plan an interstate move with a licensed moving broker coordinating authorized motor carriers nationwide." },
    hero: { eyebrow: "Interstate moving coordination", title: "Long-Distance Moving, Planned Around Your Life", body: "Build a clear interstate move plan around your inventory, dates, access needs, and destination. Vantage coordinates transportation with an authorized motor carrier suited to your route.", imageAlt: "Family reviewing an interstate move plan beside packed boxes", proofPoints: commonProofEn },
    quoteFormCopy: quoteEn("Long-Distance Move"),
    benefits: [
      { title: "Detailed inventory review", body: "We document shipment size, special items, access conditions, and requested services before carrier coordination.", icon: "package-open" },
      { title: "Route-aware planning", body: "Pickup windows, distance, and carrier availability are reviewed together so expectations are clear.", icon: "route" },
      { title: "Support through delivery", body: "Your coordinator remains available as the assigned motor carrier transports and delivers the shipment.", icon: "headphones" },
    ],
    process: [
      { title: "Share move details", body: "Tell us where, when, and what you plan to move." },
      { title: "Review inventory", body: "A coordinator confirms services, access, and special handling needs." },
      { title: "Coordinate a carrier", body: "Vantage arranges transportation with an authorized motor carrier." },
      { title: "Prepare and move", body: "Review final details, prepare for pickup, and stay informed through delivery." },
    ],
    planningTitle: "Your interstate move checklist", planningIntro: "A more accurate plan starts with complete, current information.",
    planningChecklist: ["Create a room-by-room inventory", "Measure oversized furniture and access points", "Set aside documents and irreplaceable items", "Confirm pickup and delivery contact details", "Review Your Rights and Responsibilities"],
    faqs: [
      { q: "Is Vantage the company transporting my belongings?", a: "No. Vantage Movers is a licensed interstate moving broker. We arrange transportation through FMCSA-authorized motor carriers." },
      { q: "What affects a long-distance estimate?", a: "Inventory, shipment weight or volume, distance, packing, storage, access conditions, dates, and requested services can affect an estimate." },
      { q: "When will I know my assigned carrier?", a: "Carrier assignment depends on route, dates, service needs, and availability. Your coordinator will provide the carrier information as part of the reservation and coordination process." },
      { q: "Can my dates remain flexible?", a: "Yes. Discuss preferred dates and acceptable pickup windows with your coordinator so available options can be reviewed." },
    ], relatedServiceIds: ["packing-services", "storage-options", "auto-transport"],
  },
  "auto-transport": {
    id: "auto-transport", navLabel: "Auto Transport",
    seo: { title: "Auto Transport Coordination", description: "Coordinate open or enclosed vehicle transport with route, timing, and vehicle details reviewed up front." },
    hero: { eyebrow: "Vehicle shipping coordination", title: "Auto Transport With a Clear Route Forward", body: "Coordinate vehicle shipping around your route, timing, vehicle type, and preferred transport method. We help arrange the details with qualified transport providers.", imageAlt: "Open auto carrier traveling on a wide American highway", proofPoints: commonProofEn },
    quoteFormCopy: quoteEn("Auto Transport"),
    benefits: [
      { title: "Open or enclosed options", body: "Review transport options based on vehicle needs, availability, route, and budget.", icon: "car" },
      { title: "Vehicle-specific planning", body: "Year, make, model, operability, pickup access, and destination access shape the plan.", icon: "shield" },
      { title: "Coordinated timing", body: "We align vehicle pickup expectations with your broader relocation schedule.", icon: "route" },
    ],
    process: [{ title: "Describe the vehicle", body: "Share vehicle, route, and timing details." }, { title: "Review options", body: "Compare appropriate open or enclosed transport availability." }, { title: "Confirm coordination", body: "Review the provider, pickup expectations, and preparation steps." }, { title: "Inspect at delivery", body: "Complete condition checks with the transporter at pickup and delivery." }],
    planningTitle: "Prepare your vehicle for transport", planningIntro: "Simple preparation helps create a smoother inspection and handoff.",
    planningChecklist: ["Remove personal items unless specifically permitted", "Document existing condition with dated photos", "Leave only the requested fuel level", "Confirm the vehicle starts, steers, and brakes", "Keep keys available for the transporter"],
    faqs: [{ q: "What is the difference between open and enclosed transport?", a: "Open carriers are commonly available and cost-effective. Enclosed transport offers additional environmental protection and may suit specialty vehicles." }, { q: "Can I ship personal items in my car?", a: "Policies vary by provider and applicable rules. Confirm any allowance, limits, and exclusions before pickup." }, { q: "How are pickup dates scheduled?", a: "Timing depends on route, provider availability, access, and operating conditions. Your coordinator will review the available window." }, { q: "What should I inspect at delivery?", a: "Compare the vehicle with pickup condition records and note any concerns on the delivery documentation before signing." }], relatedServiceIds: ["long-distance-moving", "residential-moving", "military-moving"],
  },
  "military-moving": {
    id: "military-moving", navLabel: "Military Moving",
    seo: { title: "Military Moving Coordination", description: "Plan PCS, PPM, or veteran relocations with timeline-aware interstate moving coordination." },
    hero: { eyebrow: "PCS and military-family planning", title: "Military Moves With Mission-Ready Coordination", body: "Organize a PCS, PPM, or veteran relocation around orders, reporting dates, household inventory, and required documentation—without implying government endorsement.", imageAlt: "Military family reviewing relocation paperwork in a packed home", proofPoints: commonProofEn },
    quoteFormCopy: quoteEn("Military Move"),
    benefits: [{ title: "Timeline-aware planning", body: "Build around orders, reporting dates, housing access, and travel plans.", icon: "shield" }, { title: "Documentation readiness", body: "Discuss requested weight tickets and records before carrier assignment.", icon: "package-open" }, { title: "Family-focused support", body: "Coordinate household goods, vehicles, packing, or storage as separate service needs.", icon: "users" }],
    process: [{ title: "Review orders and dates", body: "Share origin, destination, target dates, and known requirements." }, { title: "Build the inventory", body: "Document household goods and any requested add-on services." }, { title: "Confirm documentation", body: "Discuss carrier paperwork and requested weight-ticket needs." }, { title: "Coordinate pickup", body: "Prepare the home and maintain required records through delivery." }],
    planningTitle: "PCS and PPM planning notes", planningIntro: "Always confirm reimbursement and documentation rules with your transportation office.",
    planningChecklist: ["Confirm authorized dates and weight allowances", "Ask what documentation is required", "Separate professional gear and essential records", "Keep orders and contact details accessible", "Confirm destination access and reporting schedule"],
    faqs: [{ q: "Is Vantage affiliated with the U.S. government or military?", a: "No. Vantage is an independent licensed moving broker and does not claim government or military endorsement." }, { q: "Can weight tickets be requested?", a: "Discuss weight-ticket requirements before booking so carrier capabilities and documentation can be reviewed." }, { q: "Can a move be coordinated around orders?", a: "Yes, known dates and reporting requirements should be shared early, while recognizing that carrier windows depend on availability and route conditions." }, { q: "Who confirms reimbursement eligibility?", a: "Your military transportation or finance office is the authoritative source for reimbursement and documentation requirements." }], relatedServiceIds: ["storage-options", "auto-transport", "packing-services"],
  },
  "residential-moving": {
    id: "residential-moving", navLabel: "Residential Moving",
    seo: { title: "Residential Moving Coordination", description: "Coordinate a household move around your home inventory, timing, services, and access needs." },
    hero: { eyebrow: "Household move planning", title: "A Residential Move Built Around Your Household", body: "From apartments to multi-bedroom homes, we help organize interstate transportation around the people, belongings, access needs, and timing that make your move unique.", imageAlt: "Family planning a residential move in a bright living room", proofPoints: commonProofEn },
    quoteFormCopy: quoteEn("Residential Move"),
    benefits: [{ title: "Household inventory", body: "Room-by-room review helps reduce surprises and improve estimate accuracy.", icon: "home" }, { title: "Flexible service mix", body: "Discuss packing, storage, vehicle shipping, and specialty-item needs.", icon: "package-open" }, { title: "Access planning", body: "Stairs, elevators, parking, long carries, and building rules are captured early.", icon: "route" }],
    process: [{ title: "Describe your home", body: "Share home size, locations, dates, and access." }, { title: "Confirm inventory", body: "Review furnishings, boxes, and special items." }, { title: "Select services", body: "Add packing, storage, or other requested support." }, { title: "Coordinate moving day", body: "Prepare both locations and confirm final contacts." }],
    planningTitle: "Household move preparation", planningIntro: "A room-by-room plan makes pickup and delivery easier to manage.",
    planningChecklist: ["Declutter before the final inventory", "Label boxes by room and priority", "Reserve elevators and parking", "Photograph high-value items", "Pack a first-night essentials kit"],
    faqs: [{ q: "Do you coordinate apartment moves?", a: "Yes. Share elevator, parking, stair, loading-zone, and building-hour restrictions during planning." }, { q: "Can packing be added?", a: "Packing options may be coordinated based on inventory, materials, timing, and carrier availability." }, { q: "How do I improve estimate accuracy?", a: "Provide a complete inventory and disclose access conditions, specialty items, and requested services before final review." }, { q: "Who transports the shipment?", a: "An FMCSA-authorized motor carrier transports the shipment. Vantage acts as the licensed broker arranging the transportation." }], relatedServiceIds: ["long-distance-moving", "packing-services", "storage-options"],
  },
  "corporate-office-moving": {
    id: "corporate-office-moving", navLabel: "Corporate / Office Moving",
    seo: { title: "Corporate and Office Moving Coordination", description: "Plan interstate office relocation around downtime, inventory, access, and business continuity." },
    hero: { eyebrow: "Business relocation planning", title: "Office Moves Organized Around Business Continuity", body: "Coordinate interstate office relocation around equipment, labeled work areas, building access, timing, and the operational milestones your team needs to protect.", imageAlt: "Organized office team packing labeled workstations", proofPoints: commonProofEn },
    quoteFormCopy: quoteEn("Office Move"),
    benefits: [{ title: "Phased inventory", body: "Organize furniture, equipment, files, and departments into a move-ready plan.", icon: "office" }, { title: "Access coordination", body: "Capture loading docks, elevators, certificates, hours, and property contacts.", icon: "route" }, { title: "Downtime planning", body: "Align pickup and delivery priorities with business continuity needs.", icon: "headphones" }],
    process: [{ title: "Define scope", body: "Document sites, teams, equipment, and desired timing." }, { title: "Map constraints", body: "Confirm building rules, access, and priority assets." }, { title: "Sequence the move", body: "Create labeling and delivery priorities for the carrier." }, { title: "Reopen efficiently", body: "Verify placement plans and responsible contacts at destination." }],
    planningTitle: "Office relocation checklist", planningIntro: "Clear ownership and labeling reduce confusion at both locations.",
    planningChecklist: ["Assign an internal move lead", "Create a floor and workstation map", "Confirm building insurance requirements", "Back up data and secure sensitive records", "Label equipment and destination zones"],
    faqs: [{ q: "Can moves be planned outside business hours?", a: "Share timing restrictions early. Available windows depend on buildings, route, service scope, and carrier availability." }, { q: "Who handles IT equipment?", a: "Define disconnection, packing, chain-of-custody, and reinstallation responsibilities before booking; specialized vendors may be appropriate." }, { q: "What building details are needed?", a: "Provide loading access, elevator rules, parking, operating hours, insurance requirements, and on-site contacts." }, { q: "Does Vantage operate the moving trucks?", a: "No. Vantage is the licensed broker; an authorized motor carrier performs transportation." }], relatedServiceIds: ["packing-services", "storage-options", "long-distance-moving"],
  },
  "packing-services": {
    id: "packing-services", navLabel: "Packing Services",
    seo: { title: "Packing Services Coordination", description: "Coordinate full, partial, or fragile-item packing as part of an interstate move plan." },
    hero: { eyebrow: "Move preparation services", title: "Packing Support That Starts With the Right Plan", body: "Review full, partial, or fragile-item packing needs alongside your inventory, schedule, materials, and carrier coordination.", imageAlt: "Professional hands carefully packing fragile household items", proofPoints: commonProofEn },
    quoteFormCopy: quoteEn("Packing Services"),
    benefits: [{ title: "Full or partial packing", body: "Choose help for the whole home or focus on selected rooms and items.", icon: "package-open" }, { title: "Fragile-item planning", body: "Identify artwork, mirrors, electronics, glass, and specialty items early.", icon: "shield" }, { title: "Materials review", body: "Discuss cartons, wrapping, crating, and labeling requirements in the estimate.", icon: "box" }],
    process: [{ title: "Identify packing scope", body: "Choose full, partial, or item-specific support." }, { title: "Review special items", body: "Flag fragile, oversized, and high-value belongings." }, { title: "Confirm materials", body: "Review expected cartons, protection, and custom needs." }, { title: "Prepare essentials", body: "Keep personal documents and immediate-use items separate." }],
    planningTitle: "Prepare for packing day", planningIntro: "Decide what movers may pack and what should always remain with you.",
    planningChecklist: ["Set aside medications and documents", "Dispose of prohibited and hazardous materials", "Photograph valuable items", "Group items by destination room", "Confirm any owner-packed box requirements"],
    faqs: [{ q: "What is full-service packing?", a: "Full-service packing generally covers agreed household contents using reviewed labor and materials; exact scope must be listed in the estimate." }, { q: "Can only fragile items be packed?", a: "Partial or itemized packing may be available. Identify exact items so labor, materials, and any crating can be reviewed." }, { q: "Are packing materials included?", a: "Materials and charges should be documented in the estimate. Confirm quantities and specialty materials before service." }, { q: "What should I pack myself?", a: "Keep identification, financial records, medications, valuables, irreplaceable items, and travel essentials with you." }], relatedServiceIds: ["residential-moving", "long-distance-moving", "storage-options"],
  },
  "storage-options": {
    id: "storage-options", navLabel: "Storage Options",
    seo: { title: "Moving Storage Options", description: "Coordinate short- or longer-term storage needs as part of an interstate move." },
    hero: { eyebrow: "Flexible move timing", title: "Storage Options for the Space Between Moves", body: "When pickup and delivery dates do not align, review storage duration, access expectations, inventory, handling, and final-delivery timing as part of the move plan.", imageAlt: "Clean organized moving storage facility with labeled containers", proofPoints: commonProofEn },
    quoteFormCopy: quoteEn("Move and Storage"),
    benefits: [{ title: "Timing flexibility", body: "Bridge a closing gap, renovation, travel period, or delayed destination access.", icon: "box" }, { title: "Inventory continuity", body: "Keep the stored shipment documented as part of the coordinated move.", icon: "package-open" }, { title: "Delivery planning", body: "Discuss notice periods, access expectations, and final-delivery conditions.", icon: "route" }],
    process: [{ title: "Estimate duration", body: "Share expected storage dates and flexibility." }, { title: "Document inventory", body: "Identify shipment size and items needing special conditions." }, { title: "Review terms", body: "Confirm access, handling, fees, and delivery notice requirements." }, { title: "Schedule delivery", body: "Coordinate destination readiness and final delivery timing." }],
    planningTitle: "Questions to ask about storage", planningIntro: "Storage terms vary; make the important details explicit before booking.",
    planningChecklist: ["Confirm minimum charges and billing intervals", "Ask about access while stored", "Review prohibited and sensitive items", "Understand redelivery notice requirements", "Keep a copy of the stored inventory"],
    faqs: [{ q: "Can storage be added to a long-distance move?", a: "Storage may be coordinated when available. Duration, handling, access, and redelivery terms should appear in your move documents." }, { q: "Will I have access to my items?", a: "Access policies vary and may require notice or additional handling. Confirm expectations before the shipment enters storage." }, { q: "Is storage climate controlled?", a: "Conditions vary by facility and service. Do not assume climate control; request and document any required conditions." }, { q: "How is final delivery scheduled?", a: "Review the required notice, destination readiness, route, carrier availability, and any redelivery charges." }], relatedServiceIds: ["long-distance-moving", "residential-moving", "packing-services"],
  },
  "senior-moving": {
    id: "senior-moving", navLabel: "Senior Moving",
    seo: { title: "Senior Moving Coordination", description: "Plan a calm interstate senior relocation with family, inventory, access, packing, and timing considered together." },
    hero: { eyebrow: "Thoughtful relocation planning", title: "Senior Moves With Clarity, Patience, and Care", body: "Create a calm interstate move plan with the older adult, family, community contacts, inventory, access, packing, and destination readiness considered together.", imageAlt: "Older adult and family calmly reviewing a move plan", proofPoints: commonProofEn },
    quoteFormCopy: quoteEn("Senior Move"),
    benefits: [{ title: "Family-inclusive planning", body: "Keep authorized relatives and community contacts aligned on timing and responsibilities.", icon: "users" }, { title: "Downsizing support plan", body: "Separate moving, gifting, donating, disposal, and storage decisions before inventory review.", icon: "home" }, { title: "Gentle pacing", body: "Build time for decisions, labeling, essentials, and destination setup.", icon: "headphones" }],
    process: [{ title: "Choose decision-makers", body: "Confirm the customer and authorized family contacts." }, { title: "Sort the household", body: "Decide what moves, stores, donates, or stays." }, { title: "Plan both homes", body: "Review access, room layouts, and priority placement." }, { title: "Prepare arrival", body: "Keep medicines, records, comfort items, and contacts accessible." }],
    planningTitle: "A calmer senior move", planningIntro: "Start early and make decisions in manageable stages.",
    planningChecklist: ["Confirm who may approve move changes", "Create a simple destination floor plan", "Keep medical and legal records with family", "Label high-priority comfort items", "Coordinate community access and move-in hours"],
    faqs: [{ q: "Can family members participate in planning?", a: "Yes, with the customer's authorization. Establish one primary contact and clear decision responsibilities." }, { q: "Do you provide downsizing or estate services?", a: "Vantage coordinates transportation. Separate downsizing, donation, estate, or organizing professionals may be needed." }, { q: "Can packing and storage be included?", a: "Discuss requested services during inventory review so availability, scope, and charges can be documented." }, { q: "How can we reduce moving-day stress?", a: "Start early, label clearly, protect routines, keep essentials nearby, and confirm destination access and key contacts." }], relatedServiceIds: ["residential-moving", "packing-services", "storage-options"],
  },
};

const esCopy: Record<ServiceId, Pick<Seed, "navLabel" | "seo" | "hero" | "quoteFormCopy" | "benefits" | "process" | "planningTitle" | "planningIntro" | "planningChecklist" | "faqs">> = {
  "long-distance-moving": { navLabel: "Mudanzas de larga distancia", seo: { title: "Coordinación de mudanzas de larga distancia", description: "Planifique una mudanza interestatal con un corredor autorizado que coordina transportistas autorizados." }, hero: { eyebrow: "Coordinación de mudanzas interestatales", title: "Mudanzas de larga distancia planificadas para su vida", body: "Prepare un plan claro según su inventario, fechas, acceso y destino. Vantage coordina el transporte con un transportista autorizado para su ruta.", imageAlt: "Familia revisando un plan de mudanza interestatal junto a cajas", proofPoints: commonProofEs }, quoteFormCopy: quoteEs("su mudanza de larga distancia"), benefits: [{ title: "Inventario detallado", body: "Documentamos el tamaño, artículos especiales, acceso y servicios solicitados.", icon: "package-open" }, { title: "Planificación de ruta", body: "Revisamos ventanas, distancia y disponibilidad en conjunto.", icon: "route" }, { title: "Apoyo hasta la entrega", body: "Su coordinador permanece disponible durante el proceso.", icon: "headphones" }], process: [{ title: "Comparta los detalles", body: "Indique dónde, cuándo y qué desea mudar." }, { title: "Revise el inventario", body: "Confirmamos servicios, acceso y manejo especial." }, { title: "Coordinamos un transportista", body: "Vantage organiza el transporte con un transportista autorizado." }, { title: "Prepárese para la mudanza", body: "Revise los detalles finales y manténgase informado." }], planningTitle: "Lista para su mudanza interestatal", planningIntro: "Un plan preciso comienza con información completa.", planningChecklist: ["Prepare un inventario por habitación", "Mida muebles y puntos de acceso", "Separe documentos y objetos irremplazables", "Confirme contactos de recogida y entrega", "Revise sus derechos y responsabilidades"], faqs: [{ q: "¿Vantage transporta mis pertenencias?", a: "No. Vantage Movers es un corredor de mudanzas interestatales que organiza el transporte con transportistas autorizados por FMCSA." }, { q: "¿Qué afecta el estimado?", a: "El inventario, distancia, embalaje, almacenamiento, acceso, fechas y servicios solicitados pueden afectar el estimado." }, { q: "¿Cuándo sabré cuál es mi transportista?", a: "La asignación depende de la ruta, fechas, necesidades y disponibilidad. Su coordinador proporcionará la información." }, { q: "¿Pueden ser flexibles mis fechas?", a: "Sí. Comparta fechas preferidas y ventanas aceptables con su coordinador." }] },
  "auto-transport": { navLabel: "Transporte de autos", seo: { title: "Coordinación de transporte de autos", description: "Coordine transporte abierto o cerrado según la ruta, fechas y detalles del vehículo." }, hero: { eyebrow: "Coordinación de envío de vehículos", title: "Transporte de autos con una ruta clara", body: "Coordine el envío según la ruta, fechas, tipo de vehículo y método preferido con proveedores calificados.", imageAlt: "Transportador abierto de autos en una carretera estadounidense", proofPoints: commonProofEs }, quoteFormCopy: quoteEs("el transporte de su auto"), benefits: [{ title: "Opciones abiertas o cerradas", body: "Revise opciones según el vehículo, ruta, disponibilidad y presupuesto.", icon: "car" }, { title: "Plan para su vehículo", body: "El año, modelo, condición y acceso determinan el plan.", icon: "shield" }, { title: "Fechas coordinadas", body: "Alineamos la recogida con su mudanza general.", icon: "route" }], process: [{ title: "Describa el vehículo", body: "Comparta vehículo, ruta y fechas." }, { title: "Revise opciones", body: "Compare disponibilidad abierta o cerrada." }, { title: "Confirme la coordinación", body: "Revise proveedor y preparación." }, { title: "Inspeccione al entregar", body: "Documente la condición al recoger y entregar." }], planningTitle: "Prepare su vehículo", planningIntro: "La preparación facilita la inspección.", planningChecklist: ["Retire artículos personales no permitidos", "Tome fotos fechadas", "Deje el combustible solicitado", "Confirme que funciona", "Tenga las llaves disponibles"], faqs: [{ q: "¿Cuál es la diferencia entre transporte abierto y cerrado?", a: "El abierto suele ser más disponible; el cerrado ofrece protección ambiental adicional." }, { q: "¿Puedo dejar artículos personales?", a: "Las políticas varían. Confirme límites y exclusiones antes de la recogida." }, { q: "¿Cómo se programan las fechas?", a: "Dependen de ruta, acceso, condiciones y disponibilidad." }, { q: "¿Qué debo inspeccionar?", a: "Compare el vehículo con los registros y anote cualquier inquietud antes de firmar." }] },
  "military-moving": { navLabel: "Mudanzas militares", seo: { title: "Coordinación de mudanzas militares", description: "Planifique reubicaciones PCS, PPM o de veteranos según fechas y documentación." }, hero: { eyebrow: "Planificación PCS y familiar", title: "Mudanzas militares con coordinación preparada", body: "Organice una reubicación PCS, PPM o de veteranos según órdenes, fechas, inventario y documentación, sin implicar respaldo gubernamental.", imageAlt: "Familia militar revisando documentos de reubicación", proofPoints: commonProofEs }, quoteFormCopy: quoteEs("su mudanza militar"), benefits: [{ title: "Planificación por fechas", body: "Considere órdenes, vivienda y planes de viaje.", icon: "shield" }, { title: "Documentación", body: "Hable de boletos de peso antes de asignar el transportista.", icon: "package-open" }, { title: "Apoyo familiar", body: "Coordine hogar, vehículo, embalaje o almacenamiento.", icon: "users" }], process: [{ title: "Revise órdenes", body: "Comparta fechas y requisitos." }, { title: "Prepare el inventario", body: "Documente bienes y servicios." }, { title: "Confirme documentos", body: "Revise papeles y boletos requeridos." }, { title: "Coordine la recogida", body: "Mantenga los registros hasta la entrega." }], planningTitle: "Notas para PCS y PPM", planningIntro: "Confirme reglas con su oficina de transporte.", planningChecklist: ["Confirme fechas y límites de peso", "Pregunte qué documentos necesita", "Separe equipo profesional", "Mantenga órdenes accesibles", "Confirme acceso al destino"], faqs: [{ q: "¿Vantage está afiliado con el gobierno o las fuerzas armadas?", a: "No. Vantage es un corredor independiente y no afirma respaldo gubernamental o militar." }, { q: "¿Se pueden solicitar boletos de peso?", a: "Hable de los requisitos antes de reservar." }, { q: "¿Se coordina según las órdenes?", a: "Sí, comparta las fechas conocidas temprano; las ventanas dependen de disponibilidad." }, { q: "¿Quién confirma el reembolso?", a: "Su oficina militar de transporte o finanzas es la fuente autorizada." }] },
  "residential-moving": { navLabel: "Mudanzas residenciales", seo: { title: "Coordinación de mudanzas residenciales", description: "Coordine una mudanza del hogar según inventario, fechas, servicios y acceso." }, hero: { eyebrow: "Planificación del hogar", title: "Una mudanza residencial para su hogar", body: "Ayudamos a organizar el transporte interestatal según las personas, pertenencias, acceso y fechas de su hogar.", imageAlt: "Familia planificando una mudanza residencial", proofPoints: commonProofEs }, quoteFormCopy: quoteEs("su mudanza residencial"), benefits: [{ title: "Inventario del hogar", body: "La revisión por habitación mejora la precisión.", icon: "home" }, { title: "Servicios flexibles", body: "Considere embalaje, almacenamiento y vehículos.", icon: "package-open" }, { title: "Plan de acceso", body: "Registre escaleras, ascensores y estacionamiento.", icon: "route" }], process: [{ title: "Describa su hogar", body: "Comparta tamaño, lugares y acceso." }, { title: "Confirme inventario", body: "Revise muebles, cajas y especiales." }, { title: "Elija servicios", body: "Agregue apoyo solicitado." }, { title: "Coordine el día", body: "Prepare ambos lugares y contactos." }], planningTitle: "Preparación del hogar", planningIntro: "Un plan por habitación facilita el proceso.", planningChecklist: ["Depure antes del inventario", "Etiquete por habitación", "Reserve ascensores", "Fotografíe objetos valiosos", "Prepare esenciales"], faqs: [{ q: "¿Coordinan mudanzas de apartamentos?", a: "Sí. Comparta reglas de ascensor, estacionamiento y horarios." }, { q: "¿Puedo agregar embalaje?", a: "Puede coordinarse según inventario y disponibilidad." }, { q: "¿Cómo mejoro la precisión?", a: "Proporcione inventario completo y todas las condiciones de acceso." }, { q: "¿Quién transporta?", a: "Un transportista autorizado; Vantage organiza el transporte como corredor." }] },
  "corporate-office-moving": { navLabel: "Mudanzas de oficina", seo: { title: "Coordinación de mudanzas de oficina", description: "Planifique una reubicación de oficina según inventario, acceso y continuidad." }, hero: { eyebrow: "Planificación empresarial", title: "Mudanzas de oficina organizadas para su continuidad", body: "Coordine equipos, áreas etiquetadas, acceso, fechas y prioridades operativas.", imageAlt: "Equipo de oficina empacando estaciones etiquetadas", proofPoints: commonProofEs }, quoteFormCopy: quoteEs("la mudanza de su oficina"), benefits: [{ title: "Inventario por fases", body: "Organice muebles, equipos y departamentos.", icon: "office" }, { title: "Acceso coordinado", body: "Registre muelles, ascensores y requisitos.", icon: "route" }, { title: "Plan de continuidad", body: "Alinee prioridades con la operación.", icon: "headphones" }], process: [{ title: "Defina el alcance", body: "Documente sitios, equipos y fechas." }, { title: "Mapee restricciones", body: "Confirme edificios y activos prioritarios." }, { title: "Ordene la mudanza", body: "Cree etiquetas y prioridades." }, { title: "Reabra eficientemente", body: "Verifique planos y contactos." }], planningTitle: "Lista de reubicación", planningIntro: "Responsabilidades claras reducen confusión.", planningChecklist: ["Asigne un líder interno", "Cree un plano", "Confirme seguros del edificio", "Proteja datos", "Etiquete equipos"], faqs: [{ q: "¿Se puede mudar fuera del horario?", a: "Comparta restricciones; las ventanas dependen de edificios y disponibilidad." }, { q: "¿Quién maneja TI?", a: "Defina responsabilidades; puede necesitar especialistas." }, { q: "¿Qué detalles del edificio necesitan?", a: "Acceso, ascensores, estacionamiento, horarios y seguros." }, { q: "¿Vantage opera camiones?", a: "No. Vantage es el corredor; un transportista autorizado realiza el transporte." }] },
  "packing-services": { navLabel: "Servicios de embalaje", seo: { title: "Coordinación de servicios de embalaje", description: "Coordine embalaje completo, parcial o de artículos frágiles." }, hero: { eyebrow: "Preparación para la mudanza", title: "Apoyo de embalaje con el plan correcto", body: "Revise necesidades completas, parciales o frágiles junto con inventario, fechas y materiales.", imageAlt: "Manos embalando cuidadosamente artículos frágiles", proofPoints: commonProofEs }, quoteFormCopy: quoteEs("sus servicios de embalaje"), benefits: [{ title: "Embalaje completo o parcial", body: "Elija toda la casa o habitaciones seleccionadas.", icon: "package-open" }, { title: "Artículos frágiles", body: "Identifique arte, espejos y electrónicos.", icon: "shield" }, { title: "Revisión de materiales", body: "Confirme cajas, protección y etiquetado.", icon: "box" }], process: [{ title: "Defina el alcance", body: "Elija apoyo completo o parcial." }, { title: "Revise especiales", body: "Marque artículos frágiles y grandes." }, { title: "Confirme materiales", body: "Revise cajas y protección." }, { title: "Separe esenciales", body: "Conserve documentos y uso inmediato." }], planningTitle: "Prepárese para embalar", planningIntro: "Decida qué pueden embalar y qué conserva usted.", planningChecklist: ["Separe medicamentos", "Deseche materiales prohibidos", "Fotografíe objetos valiosos", "Agrupe por habitación", "Confirme requisitos"], faqs: [{ q: "¿Qué es embalaje completo?", a: "Cubre el contenido acordado con mano de obra y materiales descritos en el estimado." }, { q: "¿Pueden embalar solo lo frágil?", a: "Puede haber opciones parciales; identifique los artículos exactos." }, { q: "¿Incluye materiales?", a: "Los materiales y cargos deben documentarse en el estimado." }, { q: "¿Qué debo embalar yo?", a: "Conserve identificación, finanzas, medicinas, valores y esenciales." }] },
  "storage-options": { navLabel: "Opciones de almacenamiento", seo: { title: "Opciones de almacenamiento para mudanzas", description: "Coordine almacenamiento a corto o largo plazo dentro de una mudanza interestatal." }, hero: { eyebrow: "Flexibilidad entre fechas", title: "Almacenamiento para el espacio entre mudanzas", body: "Revise duración, acceso, inventario y entrega final cuando las fechas no coinciden.", imageAlt: "Instalación limpia de almacenamiento con contenedores etiquetados", proofPoints: commonProofEs }, quoteFormCopy: quoteEs("su mudanza y almacenamiento"), benefits: [{ title: "Fechas flexibles", body: "Cubra cierres, obras o acceso retrasado.", icon: "box" }, { title: "Inventario continuo", body: "Mantenga documentado el envío almacenado.", icon: "package-open" }, { title: "Plan de entrega", body: "Revise avisos, acceso y condiciones.", icon: "route" }], process: [{ title: "Calcule duración", body: "Comparta fechas esperadas." }, { title: "Documente inventario", body: "Identifique tamaño y condiciones." }, { title: "Revise términos", body: "Confirme acceso, cargos y avisos." }, { title: "Programe entrega", body: "Coordine el destino final." }], planningTitle: "Preguntas sobre almacenamiento", planningIntro: "Los términos varían; confirme los detalles.", planningChecklist: ["Confirme cargos mínimos", "Pregunte por acceso", "Revise artículos prohibidos", "Entienda el aviso de entrega", "Guarde el inventario"], faqs: [{ q: "¿Se puede agregar almacenamiento?", a: "Puede coordinarse cuando esté disponible; los términos deben aparecer en sus documentos." }, { q: "¿Tendré acceso?", a: "Las políticas varían y pueden requerir aviso o manejo adicional." }, { q: "¿Tiene control de clima?", a: "Varía según instalación; solicite y documente condiciones requeridas." }, { q: "¿Cómo se programa la entrega?", a: "Revise aviso, destino, ruta y disponibilidad." }] },
  "senior-moving": { navLabel: "Mudanzas para personas mayores", seo: { title: "Coordinación de mudanzas para personas mayores", description: "Planifique una reubicación tranquila con familia, inventario, embalaje y fechas." }, hero: { eyebrow: "Planificación considerada", title: "Mudanzas para mayores con claridad y paciencia", body: "Prepare un plan tranquilo con la persona mayor, familia, comunidad, inventario y destino.", imageAlt: "Persona mayor y familia revisando un plan de mudanza", proofPoints: commonProofEs }, quoteFormCopy: quoteEs("la mudanza de una persona mayor"), benefits: [{ title: "Plan familiar", body: "Mantenga alineados a familiares autorizados.", icon: "users" }, { title: "Plan para reducir", body: "Separe mudanza, donación y almacenamiento.", icon: "home" }, { title: "Ritmo tranquilo", body: "Deje tiempo para decisiones y esenciales.", icon: "headphones" }], process: [{ title: "Elija responsables", body: "Confirme contactos autorizados." }, { title: "Organice el hogar", body: "Decida qué se muda o dona." }, { title: "Planifique ambos hogares", body: "Revise acceso y distribución." }, { title: "Prepare la llegada", body: "Mantenga medicinas y registros accesibles." }], planningTitle: "Una mudanza más tranquila", planningIntro: "Comience temprano y decida por etapas.", planningChecklist: ["Confirme quién autoriza cambios", "Cree un plano simple", "Conserve registros médicos", "Etiquete objetos prioritarios", "Coordine horarios de la comunidad"], faqs: [{ q: "¿Puede participar la familia?", a: "Sí, con autorización del cliente y responsabilidades claras." }, { q: "¿Ofrecen servicios de reducción?", a: "Vantage coordina transporte; puede necesitar profesionales separados." }, { q: "¿Se puede incluir embalaje?", a: "Hable de servicios durante la revisión del inventario." }, { q: "¿Cómo reducimos el estrés?", a: "Comience temprano, etiquete, conserve rutinas y confirme contactos." }] },
};

function build(id: ServiceId, locale: ServiceLocale): ServicePageContent {
  const en = enSeeds[id];
  const isEs = locale === "es-US";
  const localized = isEs ? { ...en, ...esCopy[id] } : en;
  const slug = isEs ? slugs[id].es : slugs[id].en;
  const alternateSlug = isEs ? slugs[id].en : slugs[id].es;
  return {
    ...localized,
    locale,
    slug,
    path: isEs ? `/es/servicios/${slug}` : `/services/${slug}`,
    alternatePath: isEs ? `/services/${alternateSlug}` : `/es/servicios/${alternateSlug}`,
    hero: { ...localized.hero, desktopImage: asset(id), mobileImage: asset(id, true) },
  };
}

export const servicePages = SERVICE_IDS.flatMap((id) => [build(id, "en-US"), build(id, "es-US")]);

export function getServiceBySlug(locale: ServiceLocale, slug: string) {
  return servicePages.find((service) => service.locale === locale && service.slug === slug);
}

export function getServiceById(id: ServiceId, locale: ServiceLocale) {
  return servicePages.find((service) => service.id === id && service.locale === locale)!;
}

export const englishServices = SERVICE_IDS.map((id) => getServiceById(id, "en-US"));
export const spanishServices = SERVICE_IDS.map((id) => getServiceById(id, "es-US"));
